/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author igorm
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuBarraPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenuItem();
        mnuFuncionario = new javax.swing.JMenuItem();
        mnuFornecedor = new javax.swing.JMenuItem();
        mnuAcoes = new javax.swing.JMenu();
        mnuVenda = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercearia");

        mnuCadastro.setText("Cadastro");

        mnuCliente.setText("Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCliente);

        mnuProduto.setText("Produto");
        mnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuProduto);

        mnuFuncionario.setText("Funcionario");
        mnuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuFuncionario);

        mnuFornecedor.setText("Fornecedor");
        mnuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFornecedorActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuFornecedor);

        mnuBarraPrincipal.add(mnuCadastro);

        mnuAcoes.setText("Ações");

        mnuVenda.setText("Venda");
        mnuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendaActionPerformed(evt);
            }
        });
        mnuAcoes.add(mnuVenda);

        mnuBarraPrincipal.add(mnuAcoes);

        mnuAjuda.setText("Ajuda");
        mnuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjudaActionPerformed(evt);
            }
        });

        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuSobre);

        mnuBarraPrincipal.add(mnuAjuda);

        setJMenuBar(mnuBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        // TODO add your handling code here:
        FormCliente form = new FormCliente(this, true);
        form.setTitle("Cadastro de Clientes");
        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setVisible(true); 

    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAjudaActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        JOptionPane.showMessageDialog(this, "Software de Cadastros e Realização de Vendas. \n   Autor: Igor Maia de Souza.\n   Todos os Direitos Reervados");
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void mnuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFornecedorActionPerformed
        FormFornecedor form = new FormFornecedor(this, true);
        form.setTitle("Cadastro de Fornecedores");
        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setVisible(true); 
    }//GEN-LAST:event_mnuFornecedorActionPerformed

    private void mnuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFuncionarioActionPerformed
        FormFuncionario form = new FormFuncionario(this, true);
        form.setTitle("Cadastro de Funcionarios");
        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setVisible(true);  

    }//GEN-LAST:event_mnuFuncionarioActionPerformed

    private void mnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoActionPerformed
        FormProduto form = new FormProduto(this, true);
        form.setTitle("Cadastro de Produtos");
        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_mnuProdutoActionPerformed

    private void mnuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendaActionPerformed
        FormVendas form = new FormVendas(this, true);
        form.setTitle("Realização de Venda");
        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_mnuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnuAcoes;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuBar mnuBarraPrincipal;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuFornecedor;
    private javax.swing.JMenuItem mnuFuncionario;
    private javax.swing.JMenuItem mnuProduto;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenuItem mnuVenda;
    // End of variables declaration//GEN-END:variables
}
